name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "src/,pyproject.toml,uv.lock,resources/"
          target: "/fartlord/"
          strip_components: 0

      - name: Run commands on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /fartlord
            
            # Install uv if not installed
            if ! command -v uv &> /dev/null; then
              curl -LsSf https://astral.sh/uv/install.sh | sh
              export PATH="$HOME/.local/bin:$PATH"
            fi
            
            # Sync uv dependencies
            ~/.local/bin/uv sync --frozen
            
            # Fill env file
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > src/env/.env
            
            # Restart service that runs application
            sudo systemctl restart fartlord.service
